global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'Jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['192.168.1.13:8080']
      
  - job_name: 'Spring'
    metrics_path: /api/actuator/prometheus
    static_configs:
      - targets: ['192.168.1.13:6868']
